function win = tapwin(L,conf)
%TAPWIN generate a tapering window for a linear WFS array
%   Usage: win = tapwin(L,conf)
%          win = tapwin(L)
%
%   Input parameters:
%       L       - length of the loudspeaker array (m)
%       conf    - optional struct containing configuration variables (see
%                 SFS_config for default values)
%
%   Output parameters:
%       win     - tapering window (1xnLS)
%
%   TAPWIN(L,conf) generates a tapering window for a linear WFS loudspeaker
%   array with a length of L.
%
%   see also: wfs_brs
%

% AUTHOR: Hagen Wierstorf, Sascha Spors


%% ===== Checking of input  parameters ==================================

if nargchk(1,2,nargin)
    error('Wrong number of args. Usage: win = tapwin(L,conf)');
end

if ~isnumeric(L) || ~isscalar(L) || L<0
    error('%s: L has to be a positive scalar!',upper(mfilename));
end

if nargin<2
    useconfig = true;
elseif ~isstruct(conf)
    error('%s: conf has to be a struct.',upper(mfilename));
else
    useconfig = false;
end


%% ===== Configuration ==================================================

% Load default configuration values
if(useconfig)
    conf = SFS_config;
end

% Apply tapering window?
usetapwin = conf.usetapwin;
tapwinlen = conf.tapwinlen;
% Loudspeaker distance
LSdist = conf.LSdist;

% Number of loudspeaker
nLS = number_of_loudspeaker(L,conf);


%% ===== Calculation ====================================================
%
%    ------------------------------------------------------------
%   |                                                            |
% _|                                                              |_
%
if(usetapwin)

    % Length of window (ca. 30%, note: this will be splitted to the right
    % and left site of the array)
    %lenwin = ceil(tapwinlen*nLS)+1
    lenwin = round(tapwinlen*nLS)+2;
    %
    % Check if we have a to short window
    if lenwin<4
        win = ones(1,nLS);
    else
        % Create a hanning window with length lenwin
        %    -
        %   | |
        % _|   |_
        hannwin = hann(lenwin).^2;
        % Create tapering window
        % NOTE: the first and the last entry generated by hann are 0. Therefore we
        % are using the hanning window from its second sample until its second
        % last one. Also we have to look if we have a even or odd window length!
        if iseven(lenwin)
            win = [hannwin(2:ceil(end/2))' ...
                   ones(1,nLS-lenwin+2) ...
                   hannwin(ceil(end/2)+1:end-1)'];
        else
            win = [hannwin(2:ceil(end/2))' ...
                   ones(1,nLS-lenwin+3) ...
                   hannwin(ceil(end/2)+1:end-1)'];
        end
    end
else
    % If you want to use no tapering window:
    win=ones(1,nLS);
end
