% Creates ITD and ILD plots for the given IRs

data_sets = { ...
%    'FABIAN_RAR',               'HRIR';...
%    'KEMAR_RAR_05m',            'HRIR';...
%    'KEMAR_RAR_1m',             'HRIR';...
%    'KEMAR_RAR_2m',             'HRIR';...
%    'KEMAR_RAR_3m',             'HRIR';...
    'KEMAR_RAR_3m_small',       'HRIR';...
%    'KEMAR_RAR_3m_small2',      'HRIR';...
%    'KEMAR_RAR_3m_head_rot',    'HRIR';...
%    'FABIAN_Sputnik1',          'BRIR';...
%    'FABIAN_Sputnik2',          'BRIR';...
%    'FABIAN_Sputnik3',          'BRIR';...
%    'FABIAN_Sputnik4',          'BRIR';...
%    'FABIAN_Sputnik5',          'BRIR';...
%    'FABIAN_Sputnik6',          'BRIR';...
%    'FABIAN_Sputnik7',          'BRIR';...
%    'FABIAN_Sputnik8',          'BRIR'
};

for ii = 1:size(data_sets,1)
    conf.irsfile = ['measurements/',data_sets{ii,2},'s/',data_sets{ii,1},'.mat'];
    irs = read_irs(conf);
    itd = extract_itd(irs.left,irs.right,irs.fs);
    ild = extract_ild(irs.left,irs.right);
    gp_save('itd.txt',irs.azimuth/pi*180,itd);
    gp_save('ild.txt',irs.azimuth/pi*180,ild);
    % Plot ITD
    cmd = sprintf(...
        ['gnuplot<<EOC\n',...
         'reset\n',...
         'set terminal pngcairo size 500,375 enhanced font "Verdana,10"\n',...
         'set output "%s_itd.png"\n',...
         'set border linewidth 1.5\n',...
         'set style line 1 lc rgb "#0060ad" lt 1 lw 2\n',...
         'unset key\n',...
         'set grid\n',...
         'set lmargin 8\n',...
         'set xrange[-180:179]\n',...
         'set yrange[-1:1]\n',...
         'set xtics (-180,-135,-90,-45,0,45,90,135,179)\n',...
         'set ytics 0.25\n',...
         'set xlabel "phi (deg)"\n',...
         'set ylabel "ITD (ms)" offset "2,0"\n',...
         'plot "itd.txt" u 1:(\\$2*1000) w l ls 1\n',...
         'EOC\n'],data_sets{ii,1});
    system(cmd);
    % Plot ILD
    cmd = sprintf(...
        ['gnuplot<<EOC\n',...
         'reset\n',...
         'set terminal pngcairo size 500,375 enhanced font "Verdana,10"\n',...
         'set output "%s_ild.png"\n',...
         'set border linewidth 1.5\n',...
         'set style line 1 lc rgb "#0060ad" lt 1 lw 2\n',...
         'unset key\n',...
         'set grid\n',...
         'set lmargin 8\n',...
         'set xrange[-180:180]\n',...
         'set yrange[-28:28]\n',...
         'set xtics (-180,-135,-90,-45,0,45,90,135,179)\n',...
         'set ytics 10\n',...
         'set xlabel "phi (deg)"\n',...
         'set ylabel "ILD (dB)"\n',...
         'plot "ild.txt" u 1:2 w l ls 1\n',...
         'EOC\n'],data_sets{ii,1});
    system(cmd);
    % Remove data files
    delete('itd.txt');
    delete('ild.txt');
end

