function gp_save(file,x,y,header)
% GP_SAVE save x,y as a text file in a Gnuplot compatible format
%   Usage: gp_save(file,x,y,header)
%          gp_save(file,x,y)
%
%   Input parameters:
%       file    - filename of the data file
%       x       - x axis values
%       y       - y axis values [vector or matrix]
%       header  - header comment added before the data
%
%   GP_SAVE(file,x,y,header) saves the values of x and y in a text file in a 
%   format useable by Gnuplot
%

% AUTHOR: Hagen Wierstorf
% $LastChangedDate$
% $LastChangedRevision$
% $LastChangedBy$


%% ===== Checking of input  parameters ==================================
error(nargchk(3,4,nargin));

isargchar(file);
isargvector(x);
isargmatrix(y);
if ~exist('header','var')
    header = '';
else
    isargchar(header);
end


%% ===== Computation =====================================================

% Ensure we have column vectors
[x1,x2] = size(x);
if x1<x2
    x = x';
    y = y';
end
% Check if the data has the same length
if size(x,1)~=size(y,1)
    error('%s: x, y has to have the same length!',upper(mfilename));
end

% Write header to the file
fid = fopen(file,'w');
fprintf(fid,'# Data file generated by gp_save.m\n');
fprintf(fid,['# ',header,'\n']);
fclose(fid);
% Append the data to the file using tabulator as a delimiter between the data
dlmwrite(file,[x y],'\t','-append');
